### ISSUE TITLE
CAPABILITY_EXEC is not detected for unknwon/com package

### ISSUE THREAD

**Issue by carminecesarano** [google/capslock#153]
While scanning ssh package of [gogs](https://pkg.go.dev/gogs.io/gogs@v0.13.0) module I noticed that it doesn't report `CAPABILITY_EXEC` for the invocation of [ssh.go:73](https://github.com/gogs/gogs/blob/8869354d21ad25a1b3d17d2d1d75c811f9d53d20/internal/ssh/ssh.go#L73C25-L73C34). 
`com.ExecCmd` is an API provided by [unknwon/com](https://pkg.go.dev/github.com/unknwon/com) package which eventually invokes `exec.Command` as it can be seen here https://github.com/unknwon/com/blob/b41c64acd94be7e673c9c8301344d31cce99e06c/cmd.go#L34.

Steps to reproduce:
1. ```bash
   go install gogs.io/gogs@latest`
2. ```bash
   gogs/internal/ssh>  capslock -output json
    ```
3. One will observe that the JSON file does not contain `com.ExecCmd` API. Instead, it should be present and also mapped to `CAPABILITY_EXEC`.

**Comment by jcd2** [comment]
Thanks for the report!  The problem is that -output=json only lists a single example path for each function in your package to each capability, and it shows a shorter path to exec.Command through line 85 instead:

```
    {       
      "packageName": "ssh",
      "capability": "CAPABILITY_EXEC",
      "depPath": "gogs.io/gogs/internal/ssh.handleServerConn gogs.io/gogs/internal/ssh.handleServerConn$1 os/exec.Command",
      "path": [
        {
          "name": "gogs.io/gogs/internal/ssh.handleServerConn",
          "package": "gogs.io/gogs/internal/ssh"
        },
        {  
          "name": "gogs.io/gogs/internal/ssh.handleServerConn$1",
          "site": {
            "filename": "ssh.go",
            "line": "50",
            "column": "3"
          },
          "package": "gogs.io/gogs/internal/ssh"
        },  
        {  
          "name": "os/exec.Command",
          "site": {
            "filename": "ssh.go",
            "line": "85",
            "column": "25"
          },
          "package": "os/exec"
        }
      ],
      "packageDir": "gogs.io/gogs/internal/ssh",
      "capabilityType": "CAPABILITY_TYPE_DIRECT"
    },
```

Using -output=graph will show every edge on a path from your package to a capability.  The graph can be quite large, but it contains all the edges for e.g. a path from ssh.Listen to os/exec.Cmd.Run via unknwon/com:

```
  "gogs.io/gogs/internal/ssh.Listen" -> "gogs.io/gogs/internal/ssh.listen"
  "gogs.io/gogs/internal/ssh.listen" -> "gogs.io/gogs/internal/ssh.listen$1"
  "gogs.io/gogs/internal/ssh.listen$1" -> "gogs.io/gogs/internal/ssh.handleServerConn"
  "gogs.io/gogs/internal/ssh.handleServerConn" -> "gogs.io/gogs/internal/ssh.handleServerConn$1"
  "gogs.io/gogs/internal/ssh.handleServerConn$1" -> "github.com/unknwon/com.ExecCmd"
  "github.com/unknwon/com.ExecCmd" -> "github.com/unknwon/com.ExecCmdDir"
  "github.com/unknwon/com.ExecCmdDir" -> "github.com/unknwon/com.ExecCmdDirBytes"
  "github.com/unknwon/com.ExecCmdDirBytes" -> "(*os/exec.Cmd).Run"
  "(*os/exec.Cmd).Run" -> "CAPABILITY_EXEC"
```

We also have an output mode in development (in [this branch](https://github.com/jcd2/capslock/tree/int)) which will list every "intermediate" package on a path to a capability, and that would show a path through github.com/unknwon/com in the json output.

**Comment by algomaster99** [comment]
Thanks, @jcd2 ! I understand that we have to change mode to `output=graph.`

>  -output=json only lists a single example path for each function in your package to each capability

So the objective in this mode is to find a single example associated to the capability, right?

**Comment by jcd2** [comment]
> So the objective in this mode is to find a single example associated to the capability, right?

That's right.

**Comment by algomaster99** [comment]
Thanks! @carminecesarano, you may close this issue if it is answered for you as well :)

**Comment by carminecesarano** [comment]
Thanks, I'll close the issue.

**Comment by mdulin2** [comment]
I would recommend using the `-granularity=intermediate` flag on capslock for anybody seeing this in the future.
