### ISSUE TITLE
Ineffective check for len(packageNames) == 0

### ISSUE THREAD

**Issue by breml** [google/capslock#28]
The check `if len(packageNames) == 0` in 

https://github.com/google/capslock/blob/9fb634487fe70d4730a3452c9f8f42f50af16a67/cmd/capslock/capslock.go#L36-L38

is ineffective for the following reasons:

1. `strings.Split` does return a slice of length 1 for the empty string.
1. if the flag `-packages` is used without additional argument, this is already covered by `flag.Parse()`.
1. even if the tool is called with `capslock -packages ""`, we get the empty string and we are back to 1.

**Comment by jcd2** [comment]
Thanks for the report Lucas!  This check was left over from when we handled arguments differently.  I've deleted the check and left the behavior the same, so that running the tool without setting the flag defaults to analyzing the package in the current directory.
